require "vagrant"

Vagrant.configure("2") do |config|
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "./Berksfile"
  config.omnibus.chef_version = :latest

  ["development", "test"].each do |app_env|
    config.vm.define app_env do |master_config|
      master_config.vm.hostname = "demo-#{app_env}"
      master_config.vm.box = "opscode-ubuntu-12.04"
      master_config.vm.box_url = "http://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box"

      master_config.ssh.forward_agent = true

      master_config.vm.provider :virtualbox do |vb|
        vb.customize [
                      "modifyvm", :id,
                      "--memory", "2048",
                      "--cpus", "2",
                     ]
      end

      master_config.vm.network :private_network, :ip => "30.30.30.10"
      
      master_config.vm.provision :chef_solo do |chef|
        # chef.environments_path = "../x-chef/environments"
        # chef.data_bags_path = "../x-chef/data_bags"
        # chef.encrypted_data_bag_secret_key_path = "../.chef/data-bag-secret"
        # Don't need this for now
        # chef.json = {
        # }
        # chef.environment = app_env

        chef.run_list = [ "recipe[demo::default]" ]
        chef.log_level = :debug
      end

    end

  end
end
